// cards.js

// --- CORE DEFINITIONS ---
const TYPES = {
    FIRE: { name: 'Fire', icon: '🔥', weakness: 'WATER' }, 
    WATER: { name: 'Water', icon: '💧', weakness: 'ELECTRIC' },
    ELECTRIC: { name: 'Electric', icon: '⚡', weakness: 'GRASS' }, 
    GRASS: { name: 'Grass', icon: '🍃', weakness: 'FIRE' },
    PSYCHIC: { name: 'Psychic', icon: '🔮', weakness: 'NEUTRAL' }, 
    NEUTRAL: { name: 'Neutral', icon: '⚙️', weakness: 'PSYCHIC' },
    WILD: { name: 'Wild', icon: '🌟' }
};
const BASE_RARITIES = {
    COMMON: { name: 'Common', value: 0.25, colorClass: 'common-border' },
    UNCOMMON: { name: 'Uncommon', value: 2, colorClass: 'uncommon-border' },
    RARE: { name: 'Rare', value: 8, colorClass: 'rare-border' },
    ULTRA_RARE: { name: 'Ultra-Rare', value: 35, colorClass: 'ultra_rare-border' },
    SECRET_RARE: { name: 'Secret Rare', value: 150, colorClass: 'secret_rare-border' },
};
const FINISHES = {
    STANDARD: { name: 'Standard', multiplier: 1, className: '' },
    HOLO: { name: 'Holo', multiplier: 2, className: 'holo' },
    PRISMATIC: { name: 'Prismatic', multiplier: 3, className: 'prismatic' },
    FULL_ART: { name: 'Full Art', multiplier: 5, className: 'full-art' },
    MISPRINT: { name: 'Misprint', multiplier: 10, className: 'misprint', secret: true },
};

// --- CARD DATABASE ---
const CARD_GENERATIONS = {
    'gen1': [
        // Commons (30)
        { id: 101, name: "Sporepuff", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/sporepuff.png" },
        { id: 102, name: "Scorchshroom", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/scorchshroom.png" },
        { id: 103, name: "Dripshroom", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/dripshroom.png" },
        { id: 104, name: "Zapper", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/zapper.png" },
        { id: 105, name: "Pebblecap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/pebblecap.png" },
        { id: 106, name: "Mind Fluff", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/mind_fluff.png" },
        { id: 107, name: "Cinder Spore", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/cinder_spore.png" },
        { id: 108, name: "Dewdrop Morel", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/dewdrop_morel.png" },
        { id: 109, name: "Static Cap", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/static_cap.png" },
        { id: 110, name: "Mossy Tuft", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/mossy_tuft.png" },
        { id: 111, name: "Grit Shroom", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/grit_shroom.png" },
        { id: 112, name: "Odd Spore", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/odd_spore.png" },
        { id: 113, name: "Soot Puff", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/soot_puff.png" },
        { id: 114, name: "Puddle Cap", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/puddle_cap.png" },
        { id: 115, name: "Spark Gill", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/spark_gill.png" },
        { id: 116, name: "Fern Frond", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/fern_frond.png" },
        { id: 117, name: "Stone Root", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/stone_root.png" },
        { id: 118, name: "Whisper Bloom", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/whisper_bloom.png" },
        { id: 119, name: "Heat Bloom", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/heat_bloom.png" },
        { id: 120, name: "Bubble Cap", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/bubble_cap.png" },
        { id: 121, name: "Jolt Root", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/jolt_root.png" },
        { id: 122, name: "Sapling Cap", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/sapling_cap.png" },
        { id: 123, name: "Scrap Fungus", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/scrap_fungus.png" },
        { id: 124, name: "Haze Spore", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/haze_spore.png" },
        { id: 125, name: "Ember Morel", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/ember_morel.png" },
        { id: 126, name: "Lilypad Shroom", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/lilypad_shroom.png" },
        { id: 127, name: "Fuzzy Cap", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/fuzzy_cap.png" },
        { id: 128, name: "Thorn Puff", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/thorn_puff.png" },
        { id: 129, name: "Cogsworth", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/cogsworth.png" },
        { id: 130, name: "Dream Puff", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/dream_puff.png" },
        
        // Uncommons (25)
        { id: 131, name: "Sunsettia", type: TYPES.FIRE, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/sunsettia.png" },
        { id: 132, name: "River Reed", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/river_reed.png" },
        { id: 133, name: "Vine Lash", type: TYPES.GRASS, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/vine_lash.png" },
        { id: 134, name: "Iron Cap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/iron_cap.png", effect: { type: 'FLAT_VALUE_INCREASE', payload: { amount: 2 }}, desc: "(In Deck) Increases total Deck Value by a flat $2." },
        { id: 135, name: "Glowcap", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/glowcap.png", effect: { type: 'VALUE_MODIFIER', payload: { type: TYPES.PSYCHIC, amount: 1 } }, desc: "(In Deck) All 🔮 shrooms are worth +$1." },
        { id: 136, name: "Stoneshroom", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/stoneshroom.png" },
        { id: 137, name: "Collector's Cap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/collectors_cap.png", effect: { type: 'RARITY_SYNERGY', payload: { rarity: BASE_RARITIES.COMMON, amount: 0.25 }}, desc: "(Passive) Value +$0.25 for each Common card in deck." },
        { id: 138, name: "Shifting Spore", type: TYPES.WILD, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/shifting_spore.png", desc: "(In Deck) Counts as every element for synergy effects." },
        { id: 139, name: "Immolation Spore", type: TYPES.FIRE, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/immolation_spore.png", effect: { type: 'ADD_BURNS', payload: { amount: 1 } }, desc: "(On Keep) Gain +1 Burn for this run. This bonus is permanent." },
        { id: 140, name: "Steam Vent", type: [TYPES.FIRE, TYPES.WATER], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/steam_vent.png" },
        { id: 141, name: "Storm Cap", type: [TYPES.ELECTRIC, TYPES.WATER], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/storm_cap.png" },
        { id: 142, name: "Sun Dew", type: [TYPES.GRASS, TYPES.FIRE], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/sun_dew.png" },
        { id: 143, name: "Brain Fungus", type: [TYPES.PSYCHIC, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/brain_fungus.png" },
        { id: 144, name: "Resonant Crystal", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/resonant_crystal.png", effect: { type: 'VALUE_MODIFIER', payload: { type: TYPES.PSYCHIC, amount: 1.5 } }, desc: "(In Deck) All 🔮 shrooms are worth +$1.5." },
        { id: 145, name: "Ephemeral Bloom", type: TYPES.GRASS, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/ephemeral_bloom.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 3, value: 15 } }, desc: "(In Deck) Worth $15, but burns itself after you keep 3 more cards." },
        { id: 146, name: "Flash Spore", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/flash_spore.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 2, luck: 0.05 } }, desc: "(In Deck) Grants +5% Luck, but burns itself after you keep 2 more cards." },
        { id: 147, name: "Soaking Stone", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/soaking_stone.png", effect: { type: 'CONDITION_INCREASE', payload: { amount: 0.2 }}, desc: "(In Deck) Increases the condition of all cards found by +0.2." },
        { id: 148, name: "Murky Cap", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/murky_cap.png", effect: { type: 'RISK_REWARD', payload: { sell_bonus_percent: 0.30, luck_percent: -0.02 } }, desc: "(In Deck) +30% sell value for all cards, but gives -2% Luck." },
        { id: 149, name: "Fertile Soil", type: TYPES.GRASS, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fertile_soil.png", effect: { type: 'VALUE_MODIFIER', payload: { type: TYPES.GRASS, amount: 1 } }, desc: "(In Deck) All 🍃 shrooms are worth +$1." },
        { id: 150, name: "Voltaic Mycelium", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/voltaic_mycelium.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.ELECTRIC, amount: 0.5 } }, desc: "(Passive) Value +$0.50 for each ⚡ shroom in deck." },
        { id: 151, name: "Charred Root", type: TYPES.FIRE, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/charred_root.png", effect: { type: 'BURN_SYNERGY', payload: { amount: 2 }}, desc: "(Passive) Value +$2 for each card burned this run." },
        { id: 152, name: "Polished Pebble", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/polished_pebble.png", effect: { type: 'FLAT_CARD_VALUE_INCREASE', payload: { amount: 0.1 }}, desc: "(In Deck) Adds +$0.10 to the value of every card." },
        { id: 153, name: "Fading Echo", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fading_echo.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 5, value: 10 } }, desc: "(In Deck) Worth $10, but burns itself after you keep 5 more cards." },
        { id: 154, name: "Damp Moss", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/damp_moss.png" },
        { id: 155, name: "Market Cap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/market_cap.png", effect: { type: 'ADD_SELLS', payload: { amount: 1 } }, desc: "(On Keep) Gain +1 Sell for this run. This bonus is permanent." },

        // Rares (24)
        { id: 156, name: "Magma Cap", type: TYPES.FIRE, baseRarity: BASE_RARITIES.RARE, img: "cardart/magma_cap.png", effect: { type: 'SHOP_DISCOUNT', payload: { percent: 0.05 }}, desc: "(In Deck) All packs are 5% cheaper." },
        { id: 157, name: "Midas Morel", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/midas_morel.png", effect: { type: 'SELL_VALUE_INCREASE', payload: { percent: 0.1 }}, desc: "(In Deck) Gain +10% money from selling cards." },
        { id: 158, name: "Gem Seeker", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/gem_seeker.png", effect: { type: 'CONDITION_SYNERGY', payload: { threshold: 9.0, amount: 5 }}, desc: "(Passive) Value +$5 for each card in deck with condition 9.0+." },
        { id: 159, name: "Phoenix Cap", type: TYPES.FIRE, baseRarity: BASE_RARITIES.RARE, img: "cardart/phoenix_cap.png", effect: { type: 'BURN_SYNERGY', payload: { amount: 10 }}, desc: "(Passive) Value +$10 for each card burned this run." },
        { id: 160, name: "Thunder Truffle", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/thunder_truffle.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.ELECTRIC, amount: 2 } }, desc: "(Passive) Value +$2 for each ⚡ shroom in deck." },
        { id: 161, name: "Oracle Morel", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/oracle_morel.png", effect: { type: 'PACK_SIZE_INCREASE', payload: { amount: 1 }}, desc: "(In Deck) +1 card in every pack." },
        { id: 162, name: "Tidal Stone", type: [TYPES.WATER, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.RARE, img: "cardart/tidal_stone.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.WATER, amount: 1.5 } }, desc: "(Passive) Value +$1.50 for each 💧 shroom in deck." },
        { id: 163, name: "Crystal Conduit", type: [TYPES.ELECTRIC, TYPES.PSYCHIC], baseRarity: BASE_RARITIES.RARE, img: "cardart/crystal_conduit.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.ELECTRIC, amount: 1.5 } }, desc: "(Passive) Value +$1.50 for each ⚡ shroom in deck." },
        { id: 164, name: "Sun-Kissed Vine", type: [TYPES.GRASS, TYPES.FIRE], baseRarity: BASE_RARITIES.RARE, img: "cardart/sun_kissed_vine.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.GRASS, amount: 1.5 } }, desc: "(Passive) Value +$1.50 for each 🍃 shroom in deck." },
        { id: 165, name: "Alchemist's Morel", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/alchemists_morel.png", effect: { type: 'BURN_SYNERGY_MONEY', payload: { amount: 5 } }, desc: "(On Keep) Gain $5 instantly for each card burned this run." },
        { id: 166, name: "Pack Mule Spore", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/pack_mule_spore.png", effect: { type: 'DECK_SIZE_SYNERGY', payload: { per: 5, amount: 1 } }, desc: "(Passive) Value +$1 for every 5 cards in your deck." },
        { id: 167, name: "Investment Spore", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/investment_spore.png", effect: { type: 'VALUE_OVER_TIME', payload: { amount: 1 } }, desc: "(In Deck) Gains +$1 value for every pack you open." },
        { id: 168, name: "Double-Edged Spore", type: TYPES.WILD, baseRarity: BASE_RARITIES.RARE, img: "cardart/double_edged_spore.png", effect: { type: 'RISK_REWARD', payload: { value_multiplier: 4, negative_wild_synergy: -5 } }, desc: "(Passive) Has 4x its collection value. (In Deck) All other 🌟 cards are worth -$5." },
        { id: 169, name: "Ephemeral Fortune", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/ephemeral_fortune.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 1, value: 50 } }, desc: "(In Deck) Worth $50, but burns itself after you keep 1 more card." },
        { id: 170, name: "Spore of Greed", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/spore_of_greed.png", effect: { type: 'RISK_REWARD', payload: { sell_bonus_percent: 0.25, pack_size_penalty: 1 } }, desc: "(In Deck) +25% sell value for all cards, but -1 card per pack." },
        { id: 171, name: "Leech Spore", type: TYPES.GRASS, baseRarity: BASE_RARITIES.RARE, img: "cardart/leech_spore.png", desc: "(On Pack Open) Has a chance to lower the condition of other cards in the pack." },
        { id: 172, name: "Reflective Cap", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/reflective_cap.png", effect: { type: 'MIRROR_EFFECT' }, desc: "(In Deck) Copies the effect of another random card in your deck." },
        { id: 173, name: "Dowsing Rod", type: TYPES.WATER, baseRarity: BASE_RARITIES.RARE, img: "cardart/dowsing_rod.png", effect: { type: 'PACK_MODIFIER', payload: { type: TYPES.WATER, chance: 0.5 } }, desc: "(On Keep) The next pack you open has a 50% chance to be all 💧 cards." },
        { id: 174, name: "Forager's Friend", type: TYPES.GRASS, baseRarity: BASE_RARITIES.RARE, img: "cardart/foragers_friend.png", effect: { type: 'LUCK_INCREASE', payload: { percent: 0.03 }}, desc: "(In Deck) +3% Luck when opening packs." },
        { id: 175, name: "Static Overload", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/static_overload.png", effect: { type: 'RISK_REWARD', payload: { pack_size_increase: 1, condition_penalty: 0.5 } }, desc: "(In Deck) +1 card in every pack, but all cards found have -0.5 condition." },
        { id: 176, name: "Thought Weaver", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/thought_weaver.png", effect: { type: 'RARITY_SYNERGY', payload: { rarity: BASE_RARITIES.UNCOMMON, amount: 1 }}, desc: "(Passive) Value +$1 for each Uncommon card in deck." },
        { id: 177, name: "Scrap Heap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/scrap_heap.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.NEUTRAL, amount: 2 } }, desc: "(Passive) Value +$2 for each ⚙️ shroom in deck." },
        { id: 178, name: "Magma Root", type: TYPES.FIRE, baseRarity: BASE_RARITIES.RARE, img: "cardart/magma_root.png", effect: { type: 'CONDITION_INCREASE', payload: { amount: 0.3 }}, desc: "(In Deck) Increases the condition of all cards found by +0.3." },
        { id: 179, name: "Geyser Truffle", type: TYPES.WATER, baseRarity: BASE_RARITIES.RARE, img: "cardart/geyser_truffle.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 3, value: 40 } }, desc: "(In Deck) Worth $40, but burns itself after you keep 3 more cards." },

        // Ultra-Rares (15)
        { id: 180, name: "Sunstone Shroom", type: TYPES.FIRE, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/sunstone_shroom.png", effect: { type: 'TYPE_VALUE_MULTIPLIER', payload: { type: TYPES.FIRE, multiplier: 2 }}, desc: "(In Deck) All 🔥 shrooms are worth double." },
        { id: 181, name: "Tidal Core", type: TYPES.WATER, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/tidal_core.png", effect: { type: 'TYPE_VALUE_MULTIPLIER', payload: { type: TYPES.WATER, multiplier: 2 }}, desc: "(In Deck) All 💧 shrooms are worth double." },
        { id: 182, name: "Storm Caller", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/storm_caller.png", effect: { type: 'TYPE_VALUE_MULTIPLIER', payload: { type: TYPES.ELECTRIC, multiplier: 2 }}, desc: "(In Deck) All ⚡ shrooms are worth double." },
        { id: 183, name: "Gaia's Bloom", type: TYPES.GRASS, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/gaias_bloom.png", effect: { type: 'TYPE_VALUE_MULTIPLIER', payload: { type: TYPES.GRASS, multiplier: 2 }}, desc: "(In Deck) All 🍃 shrooms are worth double." },
        { id: 184, name: "Psionic Matrix", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/psionic_matrix.png", effect: { type: 'TYPE_VALUE_MULTIPLIER', payload: { type: TYPES.PSYCHIC, multiplier: 2 }}, desc: "(In Deck) All 🔮 shrooms are worth double." },
        { id: 185, name: "The Monolith", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/the_monolith.png", effect: { type: 'RISK_REWARD', payload: { value_multiplier: 2, pack_size_penalty: 1 } }, desc: "(Passive) Has double its collection value. (In Deck) -1 card per pack." },
        { id: 186, name: "Living Fossil", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/living_fossil.png", effect: { type: 'NEGATIVE_SYNERGY', payload: { type: TYPES.NEUTRAL, amount: -50 }}, desc: "(Passive) Value -$50 for each other ⚙️ shroom in deck." },
        { id: 187, name: "Swarm Spore", type: TYPES.GRASS, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/swarm_spore.png", effect: { type: 'DECK_SIZE_SYNERGY', payload: { per: 10, amount: 10 }}, desc: "(Passive) Value +$10 for every 10 cards in your deck." },
        { id: 188, name: "Gambler's Folly", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/gamblers_folly.png", effect: { type: 'RISK_REWARD', payload: { luck_percent: 0.10, sell_penalty_percent: 0.10 } }, desc: "(In Deck) +10% Luck, but -10% sell value on all cards." },
        { id: 189, name: "Mycelial Network", type: [TYPES.GRASS, TYPES.PSYCHIC], baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/mycelial_network.png", desc: "This card counts as both 🍃 and 🔮." },
        { id: 190, name: "Volcanic Heart", type: [TYPES.FIRE, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/volcanic_heart.png", effect: { type: 'BURN_SYNERGY', payload: { amount: 25 } }, desc: "(Passive) Value +$25 for each card burned this run." },
        { id: 191, name: "Spore of Creation", type: TYPES.WILD, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/spore_of_creation.png", effect: { type: 'FIRST_CARD_MODIFIER', payload: { count: 3, condition: 1.0 } }, desc: "(In Deck) The first 3 cards you keep each run gain +1.0 condition." },
        { id: 192, name: "Ephemeral King", type: TYPES.WILD, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/ephemeral_king.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 2, value: 250 } }, desc: "(In Deck) Worth $250, but burns itself after you keep 2 more cards." },
        { id: 193, name: "Solitary Spore", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/solitary_spore.png", effect: { type: 'LOW_DECK_SYNERGY', payload: { threshold: 10, multiplier: 2 } }, desc: "(In Deck) If you have 10 or fewer cards, this card's value is doubled." },
        { id: 194, name: "Mimic Morel", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/mimic_morel.png", effect: { type: 'COPYCAT', payload: { rarity: BASE_RARITIES.RARE } }, desc: "(In Deck) Copies the value of the most valuable Rare card in your deck." },

        // Secret Rares (5)
        { id: 195, name: "Galactic Cap", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/galactic_cap.png", effect: { type: 'FINISH_VALUE_MULTIPLIER', payload: { multiplier: 1.25 }}, desc: "(In Deck) All Holo, Prismatic, and Full Art cards are worth +25%." },
        { id: 196, name: "Primordial Spore", type: TYPES.GRASS, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/primordial_spore.png", effect: { type: 'FIRST_PACK_FREE', payload: {}}, collectionEffect: true, desc: "(Collection Effect) Your first pack purchase each run is free." },
        { id: 197, name: "World Tree Mycelium", type: TYPES.WILD, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/world_tree_mycelium.png", effect: { type: 'ALL_TYPE_SYNERGY', payload: { amount: 1 } }, desc: "(In Deck) Value +$1 for every card in your deck." },
        { id: 198, name: "Shroom of Doom", type: [TYPES.FIRE, TYPES.PSYCHIC], baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/shroom_of_doom.png", effect: { type: 'RISK_REWARD', payload: { value_multiplier: 5, burn_chance: 0.1 } }, desc: "(Passive) Has 5x its collection value. (On Keep) 10% chance to burn a random card from your deck." },
        { id: 199, name: "Chronomushroom", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/chronomushroom.png", effect: { type: 'VALUE_OVER_TIME', payload: { amount: 5 } }, desc: "(In Deck) Gains +$5 value for every pack you open." },
    ],
    'gen2': [
        // Commons (30)
        { id: 201, name: "Frosty Funnel", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/water.png" },
        { id: 202, name: "Sand Cap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/metal.png" },
        { id: 203, name: "Spark Stem", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/electric.png" },
        { id: 204, name: "Steam Puff", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/fire.png" },
        { id: 205, name: "Mud Cap", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/water.png" },
        { id: 206, name: "Sun Petal", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/grass.png" },
        { id: 207, name: "Volt Bloom", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/electric.png" },
        { id: 208, name: "Scrabblecap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/metal.png" },
        { id: 209, name: "Echo Spore", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/psychic.png" },
        { id: 210, name: "Cinder Root", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/fire.png" },
        { id: 211, name: "Mist Gill", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/water.png" },
        { id: 212, name: "Tanglevine", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/grass.png" },
        { id: 213, name: "Static Moss", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/electric.png" },
        { id: 214, name: "Iron Stem", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/metal.png" },
        { id: 215, name: "Foretelling Puff", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/psychic.png" },
        { id: 216, name: "Gravelshroom", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/metal.png" },
        { id: 217, name: "Ash Cap", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/fire.png" },
        { id: 218, name: "Springwater Bloom", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/water.png" },
        { id: 219, name: "Thicket Tuft", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/grass.png" },
        { id: 220, name: "Humming Spore", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/electric.png" },
        { id: 221, name: "Rivet Cap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/metal.png" },
        { id: 222, name: "Trance Morel", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/psychic.png" },
        { id: 223, name: "Smolder Spore", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/fire.png" },
        { id: 224, name: "Monsoon Morel", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/water.png" },
        { id: 225, name: "Sun Dew Leaf", type: TYPES.GRASS, baseRarity: BASE_RARITIES.COMMON, img: "cardart/grass.png" },
        { id: 226, name: "Charged Puff", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/electric.png" },
        { id: 227, name: "Alloy Gill", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.COMMON, img: "cardart/metal.png" },
        { id: 228, name: "Enigma Cap", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.COMMON, img: "cardart/psychic.png" },
        { id: 229, name: "Obsidian Root", type: TYPES.FIRE, baseRarity: BASE_RARITIES.COMMON, img: "cardart/fire.png" },
        { id: 230, name: "Glacier Cap", type: TYPES.WATER, baseRarity: BASE_RARITIES.COMMON, img: "cardart/water.png" },

        // Uncommons (25)
        { id: 231, name: "Geyser Gill", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/water.png" },
        { id: 232, name: "Mind Spore", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/psychic.png", effect: { type: 'LUCK_INCREASE', payload: { percent: 0.01 }}, desc: "(In Deck) +1% chance to find special finish cards." },
        { id: 233, name: "Geode Cap", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/metal.png", effect: { type: 'FLAT_VALUE_INCREASE', payload: { amount: 3 }}, desc: "(In Deck) Increases total Deck Value by a flat $3." },
        { id: 234, name: "Mirage Morel", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/psychic.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 4, value: 20 }}, desc: "(In Deck) Worth $20, but burns itself after you keep 4 more cards." },
        { id: 235, name: "Blazing Soul", type: TYPES.FIRE, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fire.png", effect: { type: 'VALUE_MODIFIER', payload: { type: TYPES.FIRE, amount: 1 }}, desc: "(In Deck) All 🔥 shrooms are worth +$1." },
        { id: 236, name: "Ocean Soul", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/water.png", effect: { type: 'VALUE_MODIFIER', payload: { type: TYPES.WATER, amount: 1 }}, desc: "(In Deck) All 💧 shrooms are worth +$1." },
        { id: 237, name: "Quicksand Cap", type: [TYPES.WATER, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fire.png" },
        { id: 238, name: "Sunstone Petal", type: [TYPES.FIRE, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fire.png" },
        { id: 239, name: "Magnetic Spore", type: [TYPES.ELECTRIC, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/electric.png" },
        { id: 240, name: "Wildwood Heart", type: [TYPES.GRASS, TYPES.WILD], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/grass.png" },
        { id: 241, name: "Synergy Spore", type: TYPES.WILD, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/wild.png", effect: { type: 'RARITY_SYNERGY', payload: { rarity: BASE_RARITIES.UNCOMMON, amount: 0.5 }}, desc: "(Passive) Value +$0.50 for each Uncommon card in deck." },
        { id: 242, name: "Amplifying Crystal", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/psychic.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.PSYCHIC, amount: 0.75 } }, desc: "(Passive) Value +$0.75 for each 🔮 shroom in deck." },
        { id: 243, name: "Slagshroom", type: TYPES.FIRE, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fire.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.FIRE, amount: 0.5 } }, desc: "(Passive) Value +$0.50 for each 🔥 shroom in deck." },
        { id: 244, name: "Tidal Bloom", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/water.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.WATER, amount: 0.5 } }, desc: "(Passive) Value +$0.50 for each 💧 shroom in deck." },
        { id: 245, name: "Overgrowth", type: TYPES.GRASS, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/grass.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.GRASS, amount: 0.5 } }, desc: "(Passive) Value +$0.50 for each 🍃 shroom in deck." },
        { id: 246, name: "Scrap Plate", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/metal.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.NEUTRAL, amount: 0.5 } }, desc: "(Passive) Value +$0.50 for each ⚙️ shroom in deck." },
        { id: 247, name: "Cauterize Cap", type: TYPES.FIRE, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fire.png", effect: { type: 'BURN_SYNERGY', payload: { amount: 3 }}, desc: "(Passive) Value +$3 for each card burned this run." },
        { id: 248, name: "Petrified Spore", type: [TYPES.GRASS, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/wild.png" },
        { id: 249, name: "Focusing Lens", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/psychic.png", effect: { type: 'LUCK_INCREASE', payload: { percent: 0.02 } }, desc: "(In Deck) +2% Luck." },
        { id: 250, name: "Flash Flood Fungus", type: [TYPES.WATER, TYPES.ELECTRIC], baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/psychic.png" },
        { id: 251, name: "Short Circuit", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/electric.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 3, value: 18 } }, desc: "(In Deck) Worth $18, but burns itself after you keep 3 more cards." },
        { id: 252, name: "Verdant Idol", type: TYPES.GRASS, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/grass.png" },
        { id: 253, name: "Thinking Cap", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/psychic.png" },
        { id: 254, name: "Saturated Spore", type: TYPES.WATER, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/water.png" },
        { id: 255, name: "Molten Core", type: TYPES.FIRE, baseRarity: BASE_RARITIES.UNCOMMON, img: "cardart/fire.png" },

        // Rares (23)
        { id: 256, name: "Volcanic Root", type: TYPES.FIRE, baseRarity: BASE_RARITIES.RARE, img: "cardart/fire.png", effect: { type: 'FLAT_VALUE_INCREASE', payload: { amount: 5 }}, desc: "(In Deck) Increases total Deck Value by a flat $5." },
        { id: 257, name: "Forest's Heart", type: TYPES.GRASS, baseRarity: BASE_RARITIES.RARE, img: "cardart/grass.png", effect: { type: 'MULTI_TYPE_SYNERGY', payload: { types: [TYPES.GRASS, TYPES.WATER], amount: 1.5 }}, desc: "(Passive) Value +$1.5 for each 🍃 and 💧 card in deck." },
        { id: 258, name: "Spore Warden", type: TYPES.GRASS, baseRarity: BASE_RARITIES.RARE, img: "cardart/grass.png", effect: { type: 'NAME_SYNERGY', payload: { keyword: 'spore', amount: 3 }}, desc: "(Passive) Value +$3 for each card in your deck with 'Spore' in its name." },
        { id: 259, name: "Symbiotic Mycelium", type: TYPES.WILD, baseRarity: BASE_RARITIES.RARE, img: "cardart/wild.png", effect: { type: 'MULTI_TYPE_SYNERGY', payload: { types: [TYPES.GRASS, TYPES.PSYCHIC], amount: 2 }}, desc: "(Passive) Value +$2 for each 🍃 and 🔮 card in deck." },
        { id: 260, name: "Chrono-Cap", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/psychic.png", effect: { type: 'PACK_COUNT_SYNERGY', payload: { per: 2, amount: 1 } }, desc: "(Passive) Value +$1 for every 2 packs opened this run." },
        { id: 261, name: "Forge-Shroom", type: TYPES.FIRE, baseRarity: BASE_RARITIES.RARE, img: "cardart/fire.png", effect: { type: 'VALUE_MODIFIER', payload: { type: TYPES.NEUTRAL, amount: 2 } }, desc: "(In Deck) All ⚙️ shrooms are worth +$2." },
        { id: 262, name: "Purifying Spring", type: TYPES.WATER, baseRarity: BASE_RARITIES.RARE, img: "cardart/water.png", effect: { type: 'CONDITION_INCREASE', payload: { amount: 0.4 }}, desc: "(In Deck) Increases the condition of all cards found by +0.4." },
        { id: 263, name: "Gambler's Truffle", type: TYPES.WILD, baseRarity: BASE_RARITIES.RARE, img: "cardart/wild.png", effect: { type: 'RISK_REWARD', payload: { luck_percent: 0.05, pack_size_penalty: 1 } }, desc: "(In Deck) +5% Luck, but -1 card per pack." },
        { id: 264, name: "Overcharged Idol", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/electric.png", effect: { type: 'RISK_REWARD', payload: { sell_bonus_percent: 0.20, luck_percent: -0.03 } }, desc: "(In Deck) +20% sell value for all cards, but -3% Luck." },
        { id: 265, name: "Recycling Spore", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/metal.png", effect: { type: 'BURN_SYNERGY_MONEY', payload: { amount: 8 } }, desc: "(On Keep) Gain $8 instantly for each card burned this run." },
        { id: 266, name: "The Specialist", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/psychic.png", effect: { type: 'SINGLE_TYPE_SYNERGY', payload: { amount: 10 }}, desc: "(Passive) If all cards in your deck share at least one type, this card is worth +$10 for each." },
        { id: 267, name: "Thornwood", type: [TYPES.GRASS, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.RARE, img: "cardart/psychic.png" },
        { id: 268, name: "Magma Geode", type: [TYPES.FIRE, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.RARE, img: "cardart/fire.png" },
        { id: 269, name: "Ephemeral Spirit", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/psychic.png", effect: { type: 'EPHEMERAL', payload: { lifespan: 2, value: 75 } }, desc: "(In Deck) Worth $75, but burns itself after you keep 2 more cards." },
        { id: 270, name: "Second Wind Spore", type: TYPES.GRASS, baseRarity: BASE_RARITIES.RARE, img: "cardart/grass.png", effect: { type: 'ADD_BURNS', payload: { amount: 2 } }, desc: "(On Keep) Gain +2 Burns for this run. This bonus is permanent." },
        { id: 271, name: "Tycoon Truffle", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/metal.png", effect: { type: 'ADD_SELLS', payload: { amount: 2 } }, desc: "(On Keep) Gain +2 Sells for this run. This bonus is permanent." },
        { id: 272, name: "Kingmaker Cap", type: TYPES.WILD, baseRarity: BASE_RARITIES.RARE, img: "cardart/wild.png", effect: { type: 'RARITY_SYNERGY', payload: { rarity: BASE_RARITIES.COMMON, amount: 0.75 }}, desc: "(Passive) Value +$0.75 for each Common card in deck." },
        { id: 273, name: "Static Field", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/electric.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.ELECTRIC, amount: 2.5 } }, desc: "(Passive) Value +$2.50 for each ⚡ shroom in deck." },
        { id: 274, name: "Inferno Bloom", type: TYPES.FIRE, baseRarity: BASE_RARITIES.RARE, img: "cardart/fire.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.FIRE, amount: 2.5 } }, desc: "(Passive) Value +$2.50 for each 🔥 shroom in deck." },
        { id: 275, name: "Deepwater Root", type: TYPES.WATER, baseRarity: BASE_RARITIES.RARE, img: "cardart/water.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.WATER, amount: 2.5 } }, desc: "(Passive) Value +$2.50 for each 💧 shroom in deck." },
        { id: 276, name: "Grasping Vines", type: TYPES.GRASS, baseRarity: BASE_RARITIES.RARE, img: "cardart/grass.png", effect: { type: 'TYPE_SYNERGY', payload: { type: TYPES.GRASS, amount: 2.5 } }, desc: "(Passive) Value +$2.50 for each 🍃 shroom in deck." },
        { id: 277, name: "Scrap Titan", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.RARE, img: "cardart/metal.png", effect: { type: 'DECK_SIZE_SYNERGY', payload: { per: 4, amount: 1 } }, desc: "(Passive) Value +$1 for every 4 cards in your deck." },
        { id: 278, name: "Precognitive Puff", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.RARE, img: "cardart/psychic.png" },
        { id: 279, name: "Rainbow Bloom", type: TYPES.WILD, baseRarity: BASE_RARITIES.RARE, img: "cardart/wild.png" },

        // Ultra-Rares (15)
        { id: 280, name: "Pristine Polisher", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/metal.png", effect: { type: 'AVERAGE_CONDITION_SYNERGY', payload: { threshold: 8.5, multiplier: 3 }}, desc: "(In Deck) If the average condition of your deck is 8.5+, this card's value is tripled." },
        { id: 281, name: "Aether Spore", type: TYPES.WILD, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/wild.png", effect: { type: 'TYPE_VALUE_MULTIPLIER', payload: { type: TYPES.WILD, multiplier: 3 }}, desc: "(In Deck) All 🌟 shrooms are worth triple." },
        { id: 282, name: "Singularity Shroom", type: [TYPES.PSYCHIC, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/psychic.png", effect: { type: 'RISK_REWARD', payload: { value_multiplier: 3, pack_size_penalty: 2 } }, desc: "(Passive) Has triple its collection value. (In Deck) -2 cards per pack." },
        { id: 283, name: "Living Forge", type: [TYPES.FIRE, TYPES.NEUTRAL], baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/fire.png", effect: { type: 'MULTI_TYPE_SYNERGY', payload: { types: [TYPES.FIRE, TYPES.NEUTRAL], amount: 4 }}, desc: "(Passive) Value +$4 for each 🔥 and ⚙️ card in deck." },
        { id: 284, name: "Market Master", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/metal.png", effect: { type: 'SELL_VALUE_INCREASE', payload: { percent: 0.25 }}, desc: "(In Deck) Gain +25% money from selling cards." },
        { id: 285, name: "Pandora's Boxwood", type: TYPES.WILD, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/wild.png", effect: { type: 'RISK_REWARD', payload: { luck_percent: 0.15, condition_penalty: 1.0 } }, desc: "(In Deck) +15% Luck, but all cards found have -1.0 condition." },
        { id: 286, name: "The Investor", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/metal.png", effect: { type: 'MONEY_SPENT_SYNERGY', payload: { percent: 0.1 }}, desc: "(In Deck) This card's value is 10% of all money you've spent this run." },
        { id: 287, name: "Perfect Specimen", type: TYPES.WILD, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/wild.png", effect: { type: 'MINIMUM_CONDITION', payload: { amount: 8.0 } }, desc: "(In Deck) All cards found have a minimum condition of 8.0." },
        { id: 288, name: "Royal Mycelium", type: TYPES.GRASS, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/grass.png", effect: { type: 'RARITY_SYNERGY', payload: { rarity: BASE_RARITIES.RARE, amount: 5 }}, desc: "(Passive) Value +$5 for each Rare card in deck." },
        { id: 289, name: "Raging Inferno", type: TYPES.FIRE, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/fire.png", effect: { type: 'BURN_SYNERGY', payload: { amount: 30 } }, desc: "(Passive) Value +$30 for each card burned this run." },
        { id: 290, name: "Maelstrom Core", type: TYPES.WATER, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/water.png", effect: { type: 'DECK_SIZE_SYNERGY', payload: { per: 1, amount: 0.5 } }, desc: "(Passive) Value +$0.50 for every card in your deck." },
        { id: 291, name: "Supercell Spore", type: TYPES.ELECTRIC, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/electric.png", effect: { type: 'PACK_SIZE_INCREASE', payload: { amount: 2 }}, desc: "(In Deck) +2 cards in every pack." },
        { id: 292, name: "Cerebral Network", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/psychic.png", effect: { type: 'UNIQUE_TYPE_SYNERGY', payload: { amount: 20 } }, desc: "(Passive) Value +$20 for each unique basic element type in your deck." },
        { id: 293, name: "Diamond Spore", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/metal.png", effect: { type: 'CONDITION_SYNERGY', payload: { threshold: 10.0, amount: 25 }}, desc: "(Passive) Value +$25 for each card in deck with condition 10.0+." },
        { id: 294, name: "Chimeric Spore", type: TYPES.WILD, baseRarity: BASE_RARITIES.ULTRA_RARE, img: "cardart/wild.png", effect: { type: 'COPYCAT', payload: { rarity: BASE_RARITIES.ULTRA_RARE } }, desc: "(In Deck) Copies the value of the most valuable Ultra-Rare card in your deck." },

        // Secret Rares
        { id: 295, name: "Elemental Harmony", type: TYPES.WILD, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/wild.png", effect: { type: 'SET_SYNERGY', payload: { types: [TYPES.FIRE, TYPES.WATER, TYPES.ELECTRIC, TYPES.GRASS, TYPES.PSYCHIC, TYPES.NEUTRAL], amount: 250 }}, desc: "(In Deck) Value +$250 if you have at least one of each of the 6 basic elements in your deck." },
        { id: 296, name: "Cosmic Mycelium", type: TYPES.WILD, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/wild.png", effect: { type: 'ALL_TYPE_SYNERGY', payload: { amount: 1.5 } }, desc: "(In Deck) Value +$1.50 for every card in your deck." },
        { id: 297, name: "The Librarian", type: TYPES.PSYCHIC, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/psychic.png", effect: { type: 'COLLECTION_BOOK_SYNERGY', payload: { per: 10, amount: 5 }}, desc: "(In Deck) Value +$5 for every 10 unique cards in your Collection Book." },
        { id: 298, name: "Fungal Supernova", type: [TYPES.FIRE, TYPES.WILD], baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/metal.png", effect: { type: 'RISK_REWARD', payload: { value_multiplier: 10, self_burn_chance: 0.05 } }, desc: "(Passive) Has 10x its collection value. (In Deck) 5% chance to burn ITSELF when you keep another card." },
        { id: 299, name: "Golden Spore", type: TYPES.NEUTRAL, baseRarity: BASE_RARITIES.SECRET_RARE, img: "cardart/metal.png", effect: { type: 'PERSISTENT_SELLS' }, desc: "(In Deck) Cards you sell from your deck this run are returned to your collection instead of being lost." },
    ]
};

const PACK_DEFINITIONS = {
    'gen1': { name: "Gen 1 Pack", cost: 10, cards: 5, cardPool: CARD_GENERATIONS['gen1'], color: "blue" },
    'gen1-elemental': { name: "Gen 1 Elemental Focus", cost: 15, cards: 5, cardPool: CARD_GENERATIONS['gen1'], color: "red", licenseCost: 100, elementalFocus: true },
    'gen1-rare': { name: "Gen 1 Rare+", cost: 35, cards: 5, cardPool: CARD_GENERATIONS['gen1'], color: "yellow", licenseCost: 200, rarityBias: 0.15 },
    'gen2': { name: "Gen 2 Pack", cost: 25, cards: 5, cardPool: CARD_GENERATIONS['gen2'], color: "purple" },
    'gen2-elemental': { name: "Gen 2 Elemental Focus", cost: 40, cards: 5, cardPool: CARD_GENERATIONS['gen2'], color: "teal", licenseCost: 500, elementalFocus: true },
    'gen2-rare': { name: "Gen 2 Rare+", cost: 75, cards: 5, cardPool: CARD_GENERATIONS['gen2'], color: "orange", licenseCost: 1000, rarityBias: 0.20 }
};

const MERCHANDISE_POOL = [
    // --- Playmats ---
    { id: 'pm_c_fire', type: 'Playmat', name: 'Scorched Earth Playmat', rarity: BASE_RARITIES.COMMON, cost: 40, img: 'playmats/fire.jpg', desc: 'Slightly increases chance of finding 🔥 cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.FIRE, upAmount: 0.15, typeDown: TYPES.GRASS, downAmount: 0.05 } } },
    { id: 'pm_c_water', type: 'Playmat', name: 'Winding River Playmat', rarity: BASE_RARITIES.COMMON, cost: 40, img: 'playmats/water.jpg', desc: 'Slightly increases chance of finding 💧 cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.WATER, upAmount: 0.15, typeDown: TYPES.FIRE, downAmount: 0.05 } } },
    { id: 'pm_u_fire', type: 'Playmat', name: 'Volcano Playmat', rarity: BASE_RARITIES.UNCOMMON, cost: 75, img: 'playmats/fire.jpg', desc: 'Increases chance of finding 🔥 cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.FIRE, upAmount: 0.2, typeDown: TYPES.GRASS, downAmount: 0.1 } } },
    { id: 'pm_u_water', type: 'Playmat', name: 'Ocean Playmat', rarity: BASE_RARITIES.UNCOMMON, cost: 75, img: 'playmats/water.jpg', desc: 'Increases chance of finding 💧 cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.WATER, upAmount: 0.2, typeDown: TYPES.FIRE, downAmount: 0.1 } } },
    { id: 'pm_u_electric', type: 'Playmat', name: 'Stormy Playmat', rarity: BASE_RARITIES.UNCOMMON, cost: 75, img: 'playmats/electric.jpg', desc: 'Increases chance of finding ⚡ cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.ELECTRIC, upAmount: 0.2, typeDown: TYPES.WATER, downAmount: 0.1 } } },
    { id: 'pm_u_grass', type: 'Playmat', name: 'Forest Playmat', rarity: BASE_RARITIES.UNCOMMON, cost: 75, img: 'playmats/grass.jpg', desc: 'Increases chance of finding 🍃 cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.GRASS, upAmount: 0.2, typeDown: TYPES.ELECTRIC, downAmount: 0.1 } } },
    { id: 'pm_u_psychic', type: 'Playmat', name: 'Cosmic Playmat', rarity: BASE_RARITIES.UNCOMMON, cost: 75, img: 'playmats/psychic.jpg', desc: 'Increases chance of finding 🔮 cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.PSYCHIC, upAmount: 0.2, typeDown: TYPES.NEUTRAL, downAmount: 0.1 } } },
    { id: 'pm_u_neutral', type: 'Playmat', name: 'Metal Playmat', rarity: BASE_RARITIES.UNCOMMON, cost: 75, img: 'playmats/metal.jpg', desc: 'Increases chance of finding ⚙️ cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.NEUTRAL, upAmount: 0.2, typeDown: TYPES.PSYCHIC, downAmount: 0.1 } } },
    { id: 'pm_r_geothermal', type: 'Playmat', name: 'Geothermal Playmat', rarity: BASE_RARITIES.RARE, cost: 150, img: 'playmats/fire.jpg', desc: 'Greatly increases chance of finding 🔥 and 💧 cards.', effect: { type: 'TYPE_BIAS_DUAL', payload: { typeUp: TYPES.FIRE, upAmount: 0.25, typeDown: TYPES.GRASS, downAmount: 0.15 } } },
    
    // --- Sleeves ---
    { id: 'sl_c_penny', type: 'Sleeves', name: 'Penny Sleeves', rarity: BASE_RARITIES.COMMON, cost: 50, img: 'sleeves/penny.jpg', desc: 'Slightly increases the condition of all cards found by +0.2.', effect: { type: 'CONDITION_INCREASE', payload: { amount: 0.2 } } },
    { id: 'sl_u_protective', type: 'Sleeves', name: 'Protective Sleeves', rarity: BASE_RARITIES.UNCOMMON, cost: 125, img: 'sleeves/protective.jpg', desc: 'Increases the condition of all cards found by +0.5.', effect: { type: 'CONDITION_INCREASE', payload: { amount: 0.5 } } },
    { id: 'sl_u_lucky', type: 'Sleeves', name: 'Lucky Sleeves', rarity: BASE_RARITIES.UNCOMMON, cost: 100, img: 'sleeves/lucky.jpg', desc: 'Slightly increases chance of special finishes (+1% Luck).', effect: { type: 'LUCK_INCREASE', payload: { percent: 0.01 } } },
    { id: 'sl_r_holo', type: 'Sleeves', name: 'Holo Sleeves', rarity: BASE_RARITIES.RARE, cost: 200, img: 'sleeves/holo.jpg', desc: 'Increases chance of special finishes (+3% Luck).', effect: { type: 'LUCK_INCREASE', payload: { percent: 0.03 } } },
    { id: 'sl_r_gilded', type: 'Sleeves', name: 'Gilded Sleeves', rarity: BASE_RARITIES.RARE, cost: 250, img: 'sleeves/gilded.jpg', desc: 'Adds +$0.50 to the value of every card.', effect: { type: 'FLAT_CARD_VALUE_INCREASE', payload: { amount: 0.50 } } },
    { id: 'sl_ur_dragon', type: 'Sleeves', name: 'Dragon Hide Sleeves', rarity: BASE_RARITIES.ULTRA_RARE, cost: 500, img: 'sleeves/dragon.jpg', desc: 'Greatly increases the condition of all cards found by +1.0.', effect: { type: 'CONDITION_INCREASE', payload: { amount: 1.0 } } },
    { id: 'sl_sr_starlight', type: 'Sleeves', name: 'Starlight Sleeves', rarity: BASE_RARITIES.SECRET_RARE, cost: 800, img: 'sleeves/starlight.jpg', desc: 'Greatly increases chance of special finishes (+5% Luck).', effect: { type: 'LUCK_INCREASE', payload: { percent: 0.05 } } },

    // --- Deck Boxes ---
    { id: 'db_c_cardboard', type: 'Deck Box', name: 'Cardboard Box', rarity: BASE_RARITIES.COMMON, cost: 50, img: 'deckbox/cardboard.jpg', desc: 'Increases max deck size by 10.', effect: { type: 'MAX_COLLECTION_INCREASE', payload: { amount: 10 } } },
    { id: 'db_u_plastic', type: 'Deck Box', name: 'Plastic Deck Box', rarity: BASE_RARITIES.UNCOMMON, cost: 100, img: 'deckbox/plastic.jpg', desc: 'Increases max deck size by 15.', effect: { type: 'MAX_COLLECTION_INCREASE', payload: { amount: 15 } } },
    { id: 'db_r_reinforced', type: 'Deck Box', name: 'Reinforced Box', rarity: BASE_RARITIES.RARE, cost: 175, img: 'deckbox/reinforced.jpg', desc: 'Increases max deck size by 25.', effect: { type: 'MAX_COLLECTION_INCREASE', payload: { amount: 25 } } },
    { id: 'db_ur_vault', type: 'Deck Box', name: 'The Vault', rarity: BASE_RARITIES.ULTRA_RARE, cost: 400, img: 'deckbox/vault.jpg', desc: 'Increases max deck size by 50.', effect: { type: 'MAX_COLLECTION_INCREASE', payload: { amount: 50 } } },

    // --- Binders ---
    { id: 'b_c_folder', type: 'Binder', name: 'Simple Folder', rarity: BASE_RARITIES.COMMON, cost: 60, desc: 'Increases sell value of Common cards by 25%.', effect: { type: 'RARITY_SELL_MODIFIER', payload: { rarity: BASE_RARITIES.COMMON, percent: 0.25 } } },
    { id: 'b_u_collector', type: 'Binder', name: "Collector's Binder", rarity: BASE_RARITIES.UNCOMMON, cost: 120, desc: 'Increases sell value of Common cards by 50%.', effect: { type: 'RARITY_SELL_MODIFIER', payload: { rarity: BASE_RARITIES.COMMON, percent: 0.5 } } },
    { id: 'b_r_trader', type: 'Binder', name: "Trader's Binder", rarity: BASE_RARITIES.RARE, cost: 250, desc: 'Increases sell value of Uncommon cards by 40%.', effect: { type: 'RARITY_SELL_MODIFIER', payload: { rarity: BASE_RARITIES.UNCOMMON, percent: 0.4 } } },
    { id: 'b_ur_pro', type: 'Binder', name: "Pro Binder", rarity: BASE_RARITIES.ULTRA_RARE, cost: 500, desc: 'Increases sell value of Rare cards by 30%.', effect: { type: 'RARITY_SELL_MODIFIER', payload: { rarity: BASE_RARITIES.RARE, percent: 0.3 } } },
    { id: 'b_sr_master', type: 'Binder', name: "Master Collection Binder", rarity: BASE_RARITIES.SECRET_RARE, cost: 1000, desc: 'Increases sell value of Ultra-Rare cards by 20%.', effect: { type: 'RARITY_SELL_MODIFIER', payload: { rarity: BASE_RARITIES.ULTRA_RARE, percent: 0.2 } } },
    
    // --- Tools ---
    { id: 't_u_token', type: 'Tool', name: "Merchant's Token", rarity: BASE_RARITIES.UNCOMMON, cost: 125, desc: 'Grants one additional Sell for the run.', effect: { type: 'ADD_SELLS', payload: { amount: 1 } } },
    { id: 't_r_glass', type: 'Tool', name: "Magnifying Glass", rarity: BASE_RARITIES.RARE, cost: 250, desc: 'Reveals average condition of packs before buying.', effect: { type: 'REVEAL_CONDITION' } },
    { id: 't_ur_ledger', type: 'Tool', name: "Executive Ledger", rarity: BASE_RARITIES.ULTRA_RARE, cost: 450, desc: 'Grants two additional Sells for the run.', effect: { type: 'ADD_SELLS', payload: { amount: 2 } } },
    
    // --- Charms ---
    { id: 'c_u_fading', type: 'Charm', name: "Fading Charm", rarity: BASE_RARITIES.UNCOMMON, cost: 80, desc: 'Ephemeral cards last for 1 extra keep.', effect: { type: 'EPHEMERAL_BOOST', payload: { amount: 1 } } },
    { id: 'c_r_ephemeral', type: 'Charm', name: "Ephemeral Charm", rarity: BASE_RARITIES.RARE, cost: 150, desc: 'Ephemeral cards last for 2 extra keeps.', effect: { type: 'EPHEMERAL_BOOST', payload: { amount: 2 } } },
    { id: 'c_r_cloth', type: 'Charm', name: "Polishing Cloth", rarity: BASE_RARITIES.RARE, cost: 300, desc: 'All cards found have a minimum condition of 4.0.', effect: { type: 'MINIMUM_CONDITION', payload: { amount: 4.0 } } },
    { id: 'c_ur_clover', type: 'Charm', name: "Lucky Clover", rarity: BASE_RARITIES.ULTRA_RARE, cost: 400, desc: '+5% Luck, but -5% sell value on all cards.', effect: { type: 'RISK_REWARD', payload: { luck_percent: 0.05, sell_penalty_percent: 0.05 } } },
    { id: 'c_ur_preservation', type: 'Charm', name: "Preservation Charm", rarity: BASE_RARITIES.ULTRA_RARE, cost: 600, desc: 'All cards found have a minimum condition of 6.0.', effect: { type: 'MINIMUM_CONDITION', payload: { amount: 6.0 } } },
    { id: 'c_sr_golden', type: 'Charm', name: "Golden Charm", rarity: BASE_RARITIES.SECRET_RARE, cost: 1000, desc: 'All cards found have a minimum condition of 7.0.', effect: { type: 'MINIMUM_CONDITION', payload: { amount: 7.0 } } }
];
